# Generated by Django 4.2.2 on 2023-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_sitelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['modifiedon']},
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
