# Generated by Django 4.2.2 on 2023-07-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_post_file_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/'),
        ),
    ]
